const mongoose = require('mongoose');

const MemberSchema = new mongoose.Schema({
    id: String,
    fullname: String,
    nick: String,
    age: String,
    birthDate: Date,
    mobile: String,
    line: String,
    lineName: String,
    lineUserId: String,
    email: String,
    coin: String,
    xp: String,
    code: String,
    discord_id: String,
    rank: String,
    interest: String,
    experience: String,
    goal: String,
    course: String,
    courses: [{
        courseId: String,
        project: { name: String, url: String }
    }],
    projects: [Number],
    stats: [Number],
    remark: String,
    slogan: String,
    youtube: String,
    facebook: String,
    github: String,
    referer: String,
    profileImage: String,
    phc_status: Boolean,
    username: String,
    password: String,
    reports: [{ type: mongoose.Schema.Types.ObjectId, ref: "Report" }],
    games: [{ name: String, id: { type: mongoose.Schema.Types.ObjectId, ref: "Game" } }],
    data: Object,
    fyncid: String,
    currentScene: String,
    lastAuthentication: { type: Date, default: Date.now },
    stat: String,
    finish: String,
    approve: String,
    items: Array,
    itemx: String,
    avatar: String,
    cworld: String,
    friendly: String,
    friends: Array,
    stage: String,
    stage2: String,
    stage3: String,
    stage4: String,
    stage5: String,
    times: Array,
    cstage: String,
    consultant: String,
    pro: String,
    con: String,
    unique: String,
    next: String,
    tempToken: String,
    google: String,
    ball: String,
    discordData: Object,
    prank: { type: String },
    eventIndex: { type: String },
    playertier: { type: Number, default: 0 },
    score: { type: Number, default: 0 },
    phcCoin: { type: String, default: 0 },
    joke_text: { type: String, default: "" },
    joke_url: { type: String, default: "" },
    contact: { ig: String, facebook: String, github: String, youtube: String },
    skill: { fogus: String, attitude: String, creativity: String, speed: String },
    about: { detail: String, clip: String },
    quota: String
}, { timestamps: { createdAt: "created_at", updatedAt: "updated_at" } });

module.exports = mongoose.model('Member', MemberSchema);